name: anugerah_mobile
description: anugerah mobile project
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1+10

environment:
  sdk: ">=3.0.6"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: 2.3.2
  flutter_screenutil: 5.9.0
  dio: 5.3.3
  dio_cache_interceptor: 3.4.3
  pretty_dio_logger: 1.3.1
  get: 4.6.5
  get_storage: 2.1.1
  intl: ^0.18.1
  flutter_easyloading: 3.0.5
  json_annotation: 4.8.1
  pinput: 3.0.1
  google_fonts: 6.1.0
  timer_count_down: 2.2.2
  flutter_html: 3.0.0-beta.2
  jwt_decoder: 2.0.1
  badges: 3.1.2
  carousel_slider: 4.2.1
  flutter_svg: 2.0.7
  flutter_form_builder: 9.1.1
  form_builder_validators: 9.0.0
  qr_flutter: 4.1.0
  transparent_image: 2.0.1
  flutter_map: 5.0.0
  latlong2: 0.9.0
  url_launcher: 6.1.14
  flutter_markdown: 0.6.17+3
  pull_to_refresh: 2.0.0
  image_picker: 1.0.4
  dotted_border: 2.1.0
  flutter_cache_manager: 3.3.1
  pdf_render: 1.4.0
  path_provider: 2.1.1
  permission_handler: 11.0.0
  external_path: 1.0.3
  calendar_date_picker2: 0.5.3
  location: 5.0.3
  signature: 5.4.0
  onesignal_flutter: 5.0.3
  flutter_onboarding_slider: 1.0.10
  photo_view: 0.14.0
  firebase_core: ^2.17.0
  firebase_crashlytics: 3.3.6

  cupertino_icons: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.6
  json_serializable: 6.7.1
  flutter_launcher_icons: 0.13.1
  flutter_dotenv: 5.1.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/sign_in/
    - assets/images/dashboard/
    - assets/images/order/
    - assets/images/placeholders/
    - assets/images/app_page/
    - assets/svg/
    - assets/svg/commons/
    - assets/svg/icons/
    - assets/svg/menu/
    - assets/svg/social_media/
    - assets/svg/on_boarding/
    - assets/json/
    - .env
